const productos = [
    {id: "prod-01",
    nombre: "Silla ErgoMax",
    precio: 159,
    categoria: "Oficina",
    imagen: "../Img/oficina/silla de oficina.png",
    descripcion: "Silla ergonómica con respaldo de malla transpirable y soporte lumbar ajustable, ideal para largas jornadas de trabajo.",
    material: "Malla transpirable y acero",
    color: "Negro",
    dimensiones: "62 x 58 x 118 cm"},

    {id: "prod-02",
    nombre: "Cómoda Sable 4",
    precio: 89,
    categoria: "Dormitorio",
    imagen: "../Img/dormitorio/comoda.png",
    descripcion: "Cómoda de cuatro cajones con diseño moderno y amplio espacio para organizar ropa y accesorios.",
    material: "MDF laminado",
    color: "Roble claro",
    dimensiones: "80 x 40 x 92 cm"},

    {id: "prod-03",
    nombre: "Espejo Aura Oval",
    precio: 99,
    categoria: "Decoración",
    imagen: "../Img/decoracion/Espejo Aura Oval.webp",
    descripcion: "Espejo decorativo ovalado con marco minimalista que aporta amplitud y elegancia a cualquier ambiente.",
    material: "Vidrio y aluminio",
    color: "Negro mate",
    dimensiones: "80 x 50 cm"},

    {id: "prod-04",
    nombre: "Sofá Atlas",
    precio: 699,
    categoria: "Sala",
    imagen: "../Img/sala/sofa.jpg",
    descripcion: "Sofá modular de tres plazas con cojines de alta densidad, disponible en cinco colores.",
    material: "Tela de poliéster y madera",
    color: "Beige",
    dimensiones: "220 x 90 x 85 cm"},

    {id: "prod-05",
    nombre: "Mesa Nórdica",
    precio: 129,
    categoria: "Sala",
    imagen: "../Img/sala/mesa centro nordica .png",
    descripcion: "Mesa de centro de estilo nórdico con acabado natural, perfecta para complementar salas y comedores.",
    material: "Madera maciza",
    color: "Natural",
    dimensiones: "100 x 60 x 45 cm"},

    {id: "prod-06",
    nombre: "Cama Tapizada Oslo",
    precio: 389,
    categoria: "Dormitorio",
    imagen: "../Img/dormitorio/cama tapizada oslo.png",
    descripcion: "Cama matrimonial con cabecera tapizada en tela gris e incluye base de soporte reforzada.",
    material: "Madera y tela",
    color: "Gris",
    dimensiones: "195 x 150 x 110 cm"},

    {id: "prod-07",
    nombre: "Comedor Oslo",
    precio: 2499,
    categoria: "Comedor",
    imagen: "../Img/comedor1.webp",
    descripcion: "Juego de comedor para seis personas con mesa de madera y sillas tapizadas de diseño contemporáneo.",
    material: "Madera maciza y tela",
    color: "Nogal",
    dimensiones: "180 x 90 x 75 cm"},
];