const productos = [
    {id: "prod-01",
    nombre: "Silla ErgoMax",
    precio: 159,
    categoria: "Oficina",
    imagen: "../Img/oficina/silla ergomax.png",
    descripcion: "Silla ergonómica con respaldo de malla transpirable y soporte lumbar ajustable, ideal para largas jornadas de trabajo.",
    material: "Malla transpirable y acero",
    color: "Negro",
    dimensiones: "62 x 58 x 118 cm"},

    {id: "prod-02",
    nombre: "Cómoda Sable 4",
    precio: 89,
    categoria: "Dormitorio",
    imagen: "../Img/dormitorio/comoda sable.png",
    descripcion: "Cómoda de cuatro cajones con diseño moderno y amplio espacio para organizar ropa y accesorios.",
    material: "MDF laminado",
    color: "Roble claro",
    dimensiones: "80 x 40 x 92 cm"},

    {id: "prod-03",
    nombre: "Espejo Aura Oval",
    precio: 99,
    categoria: "Decoración",
    imagen: "../Img/decoracion/Espejo Aura Oval.webp",
    descripcion: "Espejo decorativo ovalado con marco minimalista que aporta amplitud y elegancia a cualquier ambiente.",
    material: "Vidrio y aluminio",
    color: "Negro mate",
    dimensiones: "80 x 50 cm"},

    {id: "prod-04",
    nombre: "Sofá modular Atlas",
    precio: 699,
    categoria: "Sala",
    imagen: "../Img/sala/sofa atlas.png",
    descripcion: "Sofá modular de tres plazas con cojines de alta densidad, disponible en cinco colores.",
    material: "Tela de poliéster y madera",
    color: "Beige",
    dimensiones: "220 x 90 x 85 cm"},

    {id: "prod-05",
    nombre: "Mesa de centro Nórdica",
    precio: 129,
    categoria: "Sala",
    imagen: "../Img/sala/mesa centro nordica.png",
    descripcion: "Mesa de centro de estilo nórdico con acabado natural, perfecta para complementar salas y comedores.",
    material: "Madera maciza",
    color: "Natural",
    dimensiones: "100 x 60 x 45 cm"},

    {id: "prod-06",
    nombre: "Cama Tapizada Oslo",
    precio: 389,
    categoria: "Dormitorio",
    imagen: "../Img/dormitorio/cama oslo.png",
    descripcion: "Cama matrimonial con cabecera tapizada en tela gris e incluye base de soporte reforzada.",
    material: "Madera y tela",
    color: "Gris",
    dimensiones: "195 x 150 x 110 cm"},

    {id: "prod-07",
    nombre: "Comedor Oslo",
    precio: 2499,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor1.webp",
    descripcion: "Juego de comedor para seis personas con mesa de madera y sillas tapizadas de diseño contemporáneo.",
    material: "Madera maciza y tela",
    color: "Nogal",
    dimensiones: "180 x 90 x 75 cm"},

    {id: "prod-08",
    nombre: "Comedor Luxury",
    precio: 3299,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor luxuri.jpg",
    descripcion: "Comedor de diseño elegante para seis personas.",
    material: "Madera y tela",
    color: "Nogal",
    dimensiones: "180 x 90 x 75 cm"},

    {id: "prod-09",
    nombre: "Comedor Nórdico",
    precio: 2899,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor nordico01.webp",
    descripcion: "Comedor de estilo nórdico con acabados modernos.",
    material: "Madera maciza",
    color: "Natural",
    dimensiones: "170 x 85 x 75 cm"},
        
    {id: "prod-10",
    nombre: "Comedor Elegance",
    precio: 3599,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor elegante.webp",
    descripcion: "Comedor premium de estilo contemporáneo.",
    material: "Madera y vidrio",
    color: "Marrón",
    dimensiones: "190 x 95 x 75 cm"},
    
    {id: "prod-11",
    nombre: "Comedor Roble",
    precio: 2799,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor de roble.jpg",
    descripcion: "Comedor fabricado en madera de roble.",
    material: "Roble macizo",
    color: "Roble",
    dimensiones: "180 x 90 x 75 cm"},
    
    {id: "prod-12",
    nombre: "Comedor Premium",
    precio: 3899,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor premium.webp",
    descripcion: "Comedor de lujo con acabados exclusivos.",
    material: "Madera premium y tela",
    color: "Nogal oscuro",
    dimensiones: "200 x 100 x 75 cm"},
    
    {id: "prod-13",
    nombre: "Vanitorio Moderno",
    precio: 1299,
    categoria: "Baño",
    imagen: "../Img/baño/vanitorio1.webp",
    descripcion: "Vanitorio moderno con acabado elegante y amplio espacio de almacenamiento.",
    material: "MDF y cerámica",
    color: "Blanco",
    dimensiones: "80 x 45 x 85 cm"},

    {id: "prod-14",
    nombre: "Espejo Aura Oval",
    precio: 499,
    categoria: "Baño",
    imagen: "../Img/baño/Espejo Aura Oval.webp",
    descripcion: "Espejo ovalado decorativo ideal para baños modernos.",
    material: "Vidrio y aluminio",
    color: "Negro",
    dimensiones: "80 x 50 cm"},
    
    {id: "prod-15",
    nombre: "Gabinete Nordic",
    precio: 899,
    categoria: "Baño",
    imagen: "../Img/baño/Gabinete Nordic.png",
    descripcion: "Gabinete de baño con diseño nórdico y múltiples compartimentos.",
    material: "MDF laminado",
    color: "Roble claro",
    dimensiones: "70 x 35 x 180 cm"},
    
    {id: "prod-16",
    nombre: "Mueble Lavamanos",
    precio: 1599,
    categoria: "Baño",
    imagen: "../Img/baño/Mueble Lavamanos.jpg",
    descripcion: "Mueble para lavamanos con almacenamiento integrado.",
    material: "Madera y cerámica",
    color: "Blanco",
    dimensiones: "100 x 50 x 85 cm"},
    
    {id: "prod-17",
    nombre: "Espejo LED Premium",
    precio: 699,
    categoria: "Baño",
    imagen: "../Img/baño/Espejo LED Premium.webp",
    descripcion: "Espejo con iluminación LED integrada y diseño moderno.",
    material: "Vidrio templado",
    color: "Plateado",
    dimensiones: "90 x 60 cm"},
    
    {id: "prod-18",
    nombre: "Organizador de Baño",
    precio: 349,
    categoria: "Baño",
    imagen: "../Img/baño/Organizador de Baño.png",
    descripcion: "Organizador práctico para mantener el baño ordenado.",
    material: "Madera MDF",
    color: "Blanco",
    dimensiones: "60 x 25 x 120 cm"},
    
    {id: "prod-19",
    nombre: "Set de Terraza Bali",
    precio: 599,
    categoria: "Exterior",
    imagen: "../Img/exterior/set de terraza bali.png",
    descripcion: "Mesa de centro y 2 sillones de ratán sintético con cojines rectangulares.",
    material: "Ratán sintético y aluminio",
    color: "Marrón",
    dimensiones: "120 x 70 x 75 cm"},

    {id: "prod-20",
    nombre: "Tumbona para piscina",
    precio: 299,
    categoria: "Exterior",
    imagen: "../Img/exterior/tumbona.png",
    descripcion: "Tumbona de madera teca con posiciones ajustables para piscina.",
    material: "Madera teca",
    color: "Natural",
    dimensiones: "190 x 65 x 35 cm"},

    {id: "prod-21",
    nombre: "Sombrilla Excéntrica",
    precio: 349,
    categoria: "Exterior",
    imagen: "../Img/exterior/sombria EXCENTRICA.png",
    descripcion: "Sombrilla de 3 metros con base pesada y protección UV +50.",
    material: "Aluminio y poliéster",
    color: "Beige",
    dimensiones: "300 x 300 cm"},

    {id: "prod-22",
    nombre: "Estantería Modular Kob",
    precio: 249,
    categoria: "Almacenamiento",
    imagen: "../Img/almacenamiento/estanteria modular kob.jpg",
    descripcion: "Librero de 5 niveles estilo industrial en madera y metal.",
    material: "Madera y metal",
    color: "Roble oscuro",
    dimensiones: "80 x 35 x 180 cm"},

    {id: "prod-23",
    nombre: "Aparador Scandi",
    precio: 450,
    categoria: "Almacenamiento",
    imagen: "../Img/almacenamiento/aparador scandi.jpg",
    descripcion: "Mueble buffet con 3 cajones y puertas corredizas.",
    material: "Madera maciza",
    color: "Natural",
    dimensiones: "120 x 40 x 85 cm"},

    {id: "prod-24",
    nombre: "Baúl Organizador Loft",
    precio: 189,
    categoria: "Almacenamiento",
    imagen: "../Img/almacenamiento/Baúl Organizador.jpg",
    descripcion: "Banqueta baúl tapizada en lino gris para pie de cama.",
    material: "Lino y madera",
    color: "Gris",
    dimensiones: "90 x 40 x 45 cm"},

    {id: "prod-25",
    nombre: "Lámpara de Pie Aurora",
    precio: 119,
    categoria: "Iluminación",
    imagen: "https://http2.mlstatic.com/D_NQ_NP_2X_916840-MPE109680481028_042026-F.webp",
    descripcion: "Lámpara de pie con luz cálida ideal para salas y espacios de lectura.",
    material: "Metal y tela",
    color: "Negro",
    dimensiones: "160 x 40 cm"},

    {id: "prod-26",
    nombre: "Lámpara de Mesa Luna",
    precio: 49,
    categoria: "Iluminación",
    imagen: "https://media.falabella.com/falabellaPE/137692860_01/w=1200,h=1200,fit=pad",
    descripcion: "Lámpara de mesa compacta perfecta para escritorios y mesas de noche.",
    material: "Metal y vidrio",
    color: "Blanco",
    dimensiones: "45 x 20 cm"},

    {id: "prod-27",
    nombre: "Lámpara Colgante Nova",
    precio: 59,
    categoria: "Iluminación",
    imagen: "https://media.falabella.com/sodimacPE/2286815_01/w=1200,h=1200,fit=pad",
    descripcion: "Lámpara colgante moderna para comedores y salas.",
    material: "Metal",
    color: "Negro mate",
    dimensiones: "35 x 35 cm"},

    {id: "prod-28",
    nombre: "Sofá Seccional Minimalista Serene Comfort",
    precio: 3499,
    categoria: "Sala",
    imagen: "../Img/sala/sofa serene.png",
    descripcion: "Sofá de líneas bajas con extensión chaise longue derecha, diseñado para salas amplias y minimalistas",
    material: "Estructura interna de madera maciza y tapizado en tela texturizada de lino premium",
    color: "Beige arena",
    dimensiones: "3.20 x 1.05 x 1.75 x 0.42 m"},

    {id: "prod-29",
    nombre: "Set de Mesas de Centro Nido Double Eclipse",
    precio: 849,
    categoria: "Sala",
    imagen: "../Img/sala/mesas centro nido.png",
    descripcion: "Juego de mesas nido circulares y orgánicas que se superponen para optimizar el espacio de la sala",
    material: "Madera maciza y MDF enchapado con acabado lacado semi-mate",
    color: "Madera natural clara / Roble escandinavo",
    dimensiones: "90 x 38 cm | 70 x 32 cm"},
    
    {id: "prod-30",
    nombre: "Lámpara Colgante en Cascada Sphere Breeze",
    precio: 549,
    categoria: "Iluminación",
    imagen: "../Img/iluminacion/lampara colgante cascada.png",
    descripcion: "Set de luminarias en cascada con diseño de esferas orgánicas distribuidas a diferentes alturas",
    material: "Pantallas de papel de arroz japonés y base metálica con cables ajustables",
    color: "Blanco marfil",
    dimensiones: " Esferas: 25 x 30 x 35 cm | Caída ajustable max. 1.60 m"},
    
    {id: "prod-31",
    nombre: "Aparador Horizon Pure",
    precio: 1399,
    categoria: "Almacenamiento",
    imagen: "../Img/sala/mesa horizon pure.png",
    descripcion: "Aparador premium de perfil bajo y líneas puras con almacenamiento oculto mediante sistema push-to-open",
    material: "Madera de roble claro y MDF lacado satinado",
    color: "Blanco puro y madera natural",
    dimensiones: "1.90 m x 40 cm x 38 cm"},
    
    {id: "prod-32",
    nombre: "Sofá Seccional Aura",
    precio: 4299,
    categoria: "Sala",
    imagen: "../Img/sala/sofa aura.png",
    descripcion: "Sofá de alta gama con un innovador diseño orgánico de líneas curvas y envolventes que maximizan el confort",
    material: "Estructura interna de madera maciza reforzada y tapizado en tela texturizada premium de alta resistencia",
    color: "Blanco tiza / Marfil natural",
    dimensiones: "3.40 m x 1.10 m x 0.72 m"},
    
    {id: "prod-33",
    nombre: "Mesas de Centro Terra",
    precio: 1149,
    categoria: "Sala",
    imagen: "../Img/sala/mesas centro terra.png",
    descripcion: "Set de dos mesas auxiliares circulares con bloques macizos de vetas pronunciadas que aportan calidez natural",
    material: "Madera maciza con acabado laqueado protector semi-mate resistente a la humedad",
    color: "Madera nogal / Tonos terrosos naturales",
    dimensiones: "85 x 35 cm | 60 x 28 cm"},
    
    {id: "prod-34",
    nombre: "Librero de Arco Heritage",
    precio: 2499,
    categoria: "Almacenamiento",
    imagen: "../Img/almacenamiento/librero arco heritage.png",
    descripcion: "Estructura arquitectónica empotrada con diseño de arco clásico superior y repisas abiertas para exhibición elegante",
    material: "Placas de MDF enchapadas en madera natural de alta densidad y zócalos de madera maciza",
    color: "Marrón roble / Madera natural",
    dimensiones: "1.60 x 0.40 x 2.40 m"},
    
    {id: "prod-35",
    nombre: "Butaca de Acento Cosy",
    precio: 899,
    categoria: "Sala",
    imagen: "../Img/sala/butaca redondeada.png",
    descripcion: "Sillón individual de base baja y espaldar curvo ergonómico, ideal como pieza de acento para cerrar espacios de sala",
    material: "Estructura de madera contrachapada termoformada y tapizado en tela bouclé o algodón texturizado",
    color: "Marrón chocolate / Café texturizado",
    dimensiones: "0.82 x 0.80 x 0.75 m"},
    
    {id: "prod-36",
    nombre: "Sofá Seccional Nordic Grey",
    precio: 3699,
    categoria: "Sala",
    imagen: "../Img/sala/sofa nordic grey.png",
    descripcion: "Sofá esquinero de líneas rectas contemporáneas con cojines mullidos, ideal para salas de estar familiares",
    material: "Estructura interna de madera maciza, patas de madera clara y tapizado en tela texturizada de alto tránsito",
    color: "Gris cemento / Gris claro",
    dimensiones: "3.10 x 2.10 x 0.85 x 0.45 m"},
    
    {id: "prod-37",
    nombre: "Banquetas de Barra Scandi Wood (Set x2)",
    precio: 499,
    categoria: "Comedor",
    imagen: "../Img/comedor/banquetas de barra.png",
    descripcion: "Par de taburetes altos de diseño minimalista, perfectos para islas de cocina o barras de comedor",
    material: "Estructura de acero lacado y asiento ergonómico de madera maciza.",
    color: "Blanco puro con madera natural",
    dimensiones: "42 x 42 x 75 cm"},
    
    {id: "prod-38",
    nombre: "Mesa de Centro Minimal Cross",
    precio: 649,
    categoria: "Sala",
    imagen: "../Img/sala/mesa centro cross.png",
    descripcion: "Mesa de centro ligera de perfil bajo con base angular que optimiza la sensación de amplitud en la sala",
    material: "Superficie de MDF de alta densidad con acabado en poliuretano mate y patas de madera estructural",
    color: "Blanco satinado y madera clara",
    dimensiones: "110 x 60 x 40 cm"},
    
    {id: "prod-39",
    nombre: "Espejos Verticales Infinity Frame (Set x3)",
    precio: 599,
    categoria: "Decoración",
    imagen: "../Img/decoracion/espejos verticales infinity.png",
    descripcion: "Set de tres espejos de cuerpo entero diseñados para colgarse en serie y duplicar la luminosidad del espacio",
    material: "Cristal premium de alta definición con marco de aluminio extruido ultra delgado",
    color: "Marco negro mate",
    dimensiones: "160 x 60 x 2 cm"},
    
    {id: "prod-40",
    nombre: "Sofá Bouclé Wave",
    precio: 4899,
    categoria: "Sala",
    imagen: "../Img/sala/sofa organico.png",
    descripcion: "Sofá con zócalo bajo de madera y tapizado texturizado premium",
    material: "Estructura interna de madera maciza, base expuesta de roble natural y tapizado en tela bouclé",
    color: "Blanco roto / Marfil",
    dimensiones: "2.40 x 1.05 x 0.75 m"},
    
    {id: "prod-41",
    nombre: "Aparador Bajo Kyoto Linear",
    precio: 1899,
    categoria: "Almacenamiento",
    imagen: "../Img/almacenamiento/consola kyoto.png",
    descripcion: "Mueble de almacenamiento lineal y perfil bajo con frentes contrastantes y sistemas de apertura táctil",
    material: "Estructura de MDF de alta densidad enchapada en madera oscura y frentes lacados mate",
    color: "Negro ébano combinado con paneles crema",
    dimensiones: "2.20 x 0.45 x 0.50 m"},
    
    {id: "prod-42",
    nombre: "Mesas Nido Zen Timber (Set x3)",
    precio: 1299,
    categoria: "Sala",
    imagen: "../Img/sala/mesa centro zen.png",
    descripcion: "Juego de tres mesas bajas auxiliares de formas orgánicas asimétricas que celebran la estética wabi-sabi",
    material: "Madera de roble macizo con tratamiento texturizado mate de alta resistencia",
    color: "Madera natural tostada",
    dimensiones: "25 x 38 cm"},
    
    {id: "prod-43",
    nombre: "Óleo Abstracto Earth Textures",
    precio: 450,
    categoria: "Decoración",
    imagen: "../Img/decoracion/cuadro abstracto earth.png",
    descripcion: "Lienzo artístico de formato horizontal con texturas visuales densas en tonos tierra que unifica el entorno",
    material: "Pintura acrílica texturizada sobre lienzo canvas de algodón montado en bastidor de madera.",
    color: "Paleta de marrón café, terracota, ocre y beige",
    dimensiones: "1.50 x 0.90 m"},
    
    {id: "prod-44",
    nombre: "Sofá Seccional Brooklyn",
    precio: 3999,
    categoria: "Sala",
    imagen: "../Img/sala/sofa brooklyn.png",
    descripcion: "Amplio sofá seccional de diseño lineal contemporáneo con patas de madera inclinadas, ideal para salones de concepto abierto",
    material: "Estructura de madera maciza y tapizado en tela de lino grueso texturizado de alta resistencia",
    color: "Azul noche / Azul marino",
    dimensiones: "3.20 x 1.80 x 0.85 m"},
    
    {id: "prod-45",
    nombre: "Sillón de Acento Chester Leather",
    precio: 1149,
    categoria: "Sala",
    imagen: "../Img/sala/sillon chester.png",
    descripcion: "Sillón individual clásico de silueta robusta y brazos redondeados, perfecto para añadir carácter e historia al espacio",
    material: "Estructura de madera tratada y tapizado en cuero genuino envejecido con costuras reforzadas",
    color: "Marrón gastado / Tabaco",
    dimensiones: "85 x 80 x 78 cm"},
    
    {id: "prod-46",
    nombre: "Lámpara Colgante Amber Glow",
    precio: 289,
    categoria: "Iluminación",
    imagen: "../Img/iluminacion/lampara amber glow.png",
    descripcion: "Luminaria suspendida con pantalla de vidrio soplado translúcido que aporta una luz cálida, ambiental y muy acogedora",
    material: "Pantalla de vidrio tonalizado y base de sujeción metálica en color negro con cable regulable",
    color: "Ámbar degradado / Anaranjado traslúcido",
    dimensiones: "30 cm | Altura ajustable max. 1.20 m"},
    
    {id: "prod-47",
    nombre: "Alfombra de Piel Natural Nordic Fur",
    precio: 450,
    categoria: "Decoración",
    imagen: "../Img/decoracion/alfombra piel.png",
    descripcion: "Alfombra decorativa de silueta orgánica irregular que rompe la rigidez del suelo de concreto aportando textura y calidez",
    material: "Piel natural seleccionada y procesada con reverso antideslizante de alta durabilidad",
    color: "Beige claro / Crema natural con matices sutiles",
    dimensiones: "1.60 x 1.40 m"},
    
    {id: "prod-48",
    nombre: "Sofá Seccional Luxor Beige",
    precio: 4599,
    categoria: "Sala",
    imagen: "../Img/sala/sofa luxor.png",
    descripcion: "Sofá esquinero de gran formato y perfil bajo, diseñado con líneas ortogonales puras y mullidos cojines para el máximo confort",
    material: "Estructura interna reforzada y tapizado en tela de microfibra premium de alta suavidad y fácil limpieza",
    color: "Crema / Beige claro",
    dimensiones: "3.60 x 2.40 x 0.95 m"},
    
    {id: "prod-49",
    nombre: "Centro de Entretenimiento Mármol & Walnut",
    precio: 2899,
    categoria: "Almacenamiento",
    imagen: "../Img/almacenamiento/cde m&w.png",
    descripcion: "Sistema flotante modular de largo extendido con cajonería baja unificada y panel posterior arquitectónico retroiluminado",
    material: "Estructura de MDF enchapado en madera de nogal, frentes lacados y paneles con acabado tipo mármol calacatta",
    color: "Marrón nogal, blanco veteado y crema",
    dimensiones: "4.00 x 0.45 x 0.40 m"},
    
    {id: "prod-50",
    nombre: "Mesa de Centro Monolith",
    precio: 1499,
    categoria: "Sala",
    imagen: "../Img/sala/mesa centro monolith.png",
    descripcion: "Mesa de centro rectangular de formato bajo y volumétrico con superficie reflectante que duplica la sofisticación del espacio",
    material: "Estructura sólida de madera con revestimiento exterior de vidrio templado ahumado de alta resistencia",
    color: "Gris grafito espejado / Bronce oscuro",
    dimensiones: "1.40 x 0.90 x 0.32 m"},
    
    {id: "prod-51",
    nombre: "Set de Jarrones Zafiro (x3)",
    precio: 249,
    categoria: "Decoración",
    imagen: "../Img/decoracion/jarrones zafiro.png",
    descripcion: "Conjunto de tres vasijas ornamentales de siluetas estilizadas y orgánicas perfectas para repisas o consolas modernas",
    material: "Cerámica vitrificada moldeada a mano con acabado esmaltado mate satinado",
    color: "Gris asfalto / Bronce metalizado",
    dimensiones: "25 cm | 32 cm | 40 cm"},
    
    {id: "prod-52",
    nombre: "Sofá Seccional Envolvente Aspen",
    precio: 5499,
    categoria: "Sala",
    imagen: "../Img/sala/sofa aspen.png",
    descripcion: "Sofá esquinero de máxima capacidad en formato, diseñado con un perfil robusto y cojines extra confortables para climas cálidos y acogedores",
    material: "Estructura interna de madera maciza y tapizado en tela texturizada de chenille o tweed de alta densidad",
    color: "Gris pardo / Taupe texturizado",
    dimensiones: "4.10 x 2.20 x 0.90 m"},
    
    {id: "prod-53",
    nombre: "Araña de Techo Candelabro Medieval Ring",
    precio: 1899,
    categoria: "Iluminación",
    imagen: "../Img/iluminacion/candelabro mediaval.png",
    descripcion: "Imponente luminaria colgante de formato circular con múltiples puntos de luz expuestos que simulan velas tradicionales, ideal para techos altos",
    material: "Estructura circular de hierro forjado con acabado pavonado y cadenas de suspensión reforzadas",
    color: "Negro hierro / Grafito oscuro",
    dimensiones: "Altura regulable max. 1.20 m"},
    
    {id: "prod-54",
    nombre: "Ramas Escultóricas Forest Birch (Set x3)",
    precio: 189,
    categoria: "Decoración",
    imagen: "../Img/decoracion/ramas forest.png",
    descripcion: "Conjunto de troncos y ramas delgadas seleccionadas para colocar de pie en esquinas o repisas, aportando un toque natural y campestre",
    material: "Madera natural de abedul tratada y curada para conservación en interiores",
    color: "Blanco corteza / Gris natural",
    dimensiones: "1.50 m"},
    
    {id: "prod-55",
    nombre: "Mesa de Centro Maciza Alps",
    precio: 1399,
    categoria: "Sala",
    imagen: "../Img/sala/mesa centro alps.png",
    descripcion: "Mesa de centro rectangular baja fabricada a partir de un tablón robusto que expone la belleza e imperfección de la madera natural",
    material: "Madera maciza de pino o roble rústico con acabado protector mate contra manchas y humedad",
    color: "Madera natural envejecida",
    dimensiones: "1.40 x 0.80 x 0.35 m"},
    
<<<<<<< HEAD
    {
id: "prod-56",
nombre: "Alfombra de Piel",
precio: 1299,
categoria: "Decoración",
imagen: "../Img/decoracion/alfombra piel.png",
descripcion: "Alfombra decorativa de textura suave y elegante para salas y dormitorios.",
material: "Poliéster",
color: "Beige",
dimensiones: "200 x 150 cm"
},

{
id: "prod-57",
nombre: "Cuadro Abstracto Earth",
precio: 499,
categoria: "Decoración",
imagen: "../Img/decoracion/cuadro abstracto earth.png",
descripcion: "Cuadro decorativo con diseño abstracto inspirado en tonos tierra.",
material: "Lienzo y madera",
color: "Multicolor",
dimensiones: "90 x 60 cm"
},

{
id: "prod-58",
nombre: "Espejo Aura Oval",
precio: 899,
categoria: "Decoración",
imagen: "../Img/decoracion/Espejo Aura Oval.webp",
descripcion: "Espejo ovalado moderno ideal para salas, baños y dormitorios.",
material: "Vidrio y aluminio",
color: "Negro",
dimensiones: "80 x 50 cm"
},

{
id: "prod-59",
nombre: "Espejos Verticales Infinity",
precio: 1599,
categoria: "Decoración",
imagen: "../Img/decoracion/espejos verticales infinity.png",
descripcion: "Juego de espejos decorativos de cuerpo completo con diseño moderno.",
material: "Vidrio templado",
color: "Plateado",
dimensiones: "180 x 40 cm"
},

{
id: "prod-60",
nombre: "Jarrones Zafiro",
precio: 699,
categoria: "Decoración",
imagen: "../Img/decoracion/jarrones zafiro.png",
descripcion: "Set de jarrones decorativos de estilo contemporáneo.",
material: "Cerámica",
color: "Azul",
dimensiones: "40 cm"
},

{
id: "prod-61",
nombre: "Ramas Forest",
precio: 349,
categoria: "Decoración",
imagen: "../Img/decoracion/ramas forest.png",
descripcion: "Ramas decorativas artificiales para jarrones y centros de mesa.",
material: "PVC",
color: "Verde",
dimensiones: "120 cm"
}
=======
    {id: "prod-56",
    nombre: "Silla Con Cojín (Negra) Estructura De Aluminio",
    precio: 399,
    categoria: "Exterior",
    imagen: "https://kulhaus.com/cdn/shop/files/J0600031NN15_2_1800x1800.jpg?v=1751911140",
    descripcion: "Silla de exterior con cojín ergonómico y estructura de aluminio resistente.",
    material: "Aluminio",
    color: "Negro",
    dimensiones: "58 x 62 x 85 cm"},

    {id: "prod-57",
    nombre: "Juego de Balcón - Mesa de vidrio Redonda 60 CM + 2 Sillas Ratan",
    precio: 159.99,
    categoria: "Exterior",
    imagen: "https://media.falabella.com/sodimacPE/2711869C4_400/w=1200,h=1200,fit=pad",
    descripcion: "Juego de balcón con mesa de vidrio redonda y 2 sillas de ratán sintético.",
    material: "Vidrio y ratán sintético",
    color: "Marrón y Negro",
    dimensiones: "60 x 60 x 70 cm"},

    {id: "prod-58",
    nombre: "Silla One CB Gris Oscuro",
    precio: 299,
    categoria: "Exterior",
    imagen: "https://d20f60vzbd93dl.cloudfront.net/uploads/tienda_000634/tienda_000634_86d718a4db1629050ea18ba1e008c1cb8b1697b8_producto_large_90.jpg",
    descripcion: "Silla de exterior con diseño moderno y acabados de alta calidad.",
    material: "Polipropileno y metal",
    color: "Gris oscuro",
    dimensiones: "54 x 57 x 82 cm"},

    {id: "prod-59",
    nombre: "Credenza Doble con Puertas",
    precio: 999,
    categoria: "Almacenamiento",
    imagen: "https://visso.com.pe/wp-content/uploads/2023/02/credenza-larga.jpg",
    descripcion: "Un diseño elegante y funcional que aporta estilo y organización a tu espacio.",
    material: "Madera y metal",
    color: "Melamina",
    dimensiones: "160 x 75 x 40 cm"},

    {id: "prod-60",
    nombre: "Estante London 150cm Maple Metal Orange",
    precio: 329.99,
    categoria: "Almacenamiento",
    imagen: "https://promart.vteximg.com.br/arquivos/ids/8380628-1000-1000/144766.jpg?v=638665225704170000",
    descripcion: "El Estante London de Orange (150 cm) fusiona diseño industrial y alta resistencia.",
    material: "Maple y metal",
    color: "Orange y Maple",
    dimensiones: "150 x 72 x 33 cm"},
    
    {id: "prod-61",
    nombre: "Estante Epóxico De 04 Niveles Tipo Rejilla",
    precio: 800.00,
    categoria: "Almacenamiento",
    imagen: "https://fritecsa.com.pe/wp-content/uploads/2022/10/estante-epoxico-tipo-rejilla.webp",
    descripcion: "Este organizador profesional cuenta con una sólida estructura de acero protegida con recubrimiento epóxico anticorrosivo.",
    material: "Acero epóxico",
    color: "Gris y Negro",
    dimensiones: "183 x 122 x 46 cm"},

    {id: "prod-62",
    nombre: "Lámpara de Pie Bow Negro",
    precio: 299,
    categoria: "Iluminación",
    imagen: "https://media.falabella.com/sodimacPE/9029583_400/w=1500,h=1500,fit=cover",
    descripcion: "Lámpara de pie minimalista de acabado mate moderno.",
    material: "Estructura de metal y pantalla de tela",
    color: "Negro mate",
    dimensiones: "170 x 80 cm"},

    {id: "prod-63",
    nombre: "Lámpara de Techo Valencia 3L E27 Blanco",
    precio: 89,
    categoria: "Iluminación",
    imagen: "https://media.falabella.com/sodimacPE/2330628_02/w=1500,h=1500,fit=cover",
    descripcion: "Lámpara de techo con diseño moderno y funcionalidad.",
    material: "Plástico y metal",
    color: "Blanco",
    dimensiones: "30 x 30 cm"},

    {id: "prod-64",
    nombre: "Lámpara de Mesa Barres Gris",
    precio: 54.90,
    categoria: "Iluminación",
    imagen: "https://media.falabella.com/sodimacPE/9040145_04/w=1200,h=1200,fit=pad",
    descripcion: "Lámpara de mesa con diseño elegante y funcional.",
    material: "Metal y tela",
    color: "Gris",
    dimensiones: "45 x 20 cm"},
>>>>>>> ea92741e65a3449e178efc9412cd4e3daddc85b0
];