const productos = [
    {id: "prod-01",
    nombre: "Silla ErgoMax",
    precio: 159,
    categoria: "Oficina",
    imagen: "../Img/oficina/silla de oficina.png",
    descripcion: "Silla ergonómica con respaldo de malla transpirable y soporte lumbar ajustable, ideal para largas jornadas de trabajo.",
    material: "Malla transpirable y acero",
    color: "Negro",
    dimensiones: "62 x 58 x 118 cm"},

    {id: "prod-02",
    nombre: "Cómoda Sable 4",
    precio: 89,
    categoria: "Dormitorio",
    imagen: "../Img/dormitorio/comoda.png",
    descripcion: "Cómoda de cuatro cajones con diseño moderno y amplio espacio para organizar ropa y accesorios.",
    material: "MDF laminado",
    color: "Roble claro",
    dimensiones: "80 x 40 x 92 cm"},

    {id: "prod-03",
    nombre: "Espejo Aura Oval",
    precio: 99,
    categoria: "Decoración",
    imagen: "../Img/decoracion/Espejo Aura Oval.webp",
    descripcion: "Espejo decorativo ovalado con marco minimalista que aporta amplitud y elegancia a cualquier ambiente.",
    material: "Vidrio y aluminio",
    color: "Negro mate",
    dimensiones: "80 x 50 cm"},

    {id: "prod-04",
    nombre: "Sofá Atlas",
    precio: 699,
    categoria: "Sala",
    imagen: "../Img/sala/sofa.jpg",
    descripcion: "Sofá modular de tres plazas con cojines de alta densidad, disponible en cinco colores.",
    material: "Tela de poliéster y madera",
    color: "Beige",
    dimensiones: "220 x 90 x 85 cm"},

    {id: "prod-05",
    nombre: "Mesa Nórdica",
    precio: 129,
    categoria: "Sala",
    imagen: "../Img/sala/mesa centro nordica .png",
    descripcion: "Mesa de centro de estilo nórdico con acabado natural, perfecta para complementar salas y comedores.",
    material: "Madera maciza",
    color: "Natural",
    dimensiones: "100 x 60 x 45 cm"},

    {id: "prod-06",
    nombre: "Cama Tapizada Oslo",
    precio: 389,
    categoria: "Dormitorio",
    imagen: "../Img/dormitorio/cama tapizada oslo.png",
    descripcion: "Cama matrimonial con cabecera tapizada en tela gris e incluye base de soporte reforzada.",
    material: "Madera y tela",
    color: "Gris",
    dimensiones: "195 x 150 x 110 cm"},

    {id: "prod-07",
    nombre: "Comedor Oslo",
    precio: 2499,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor1.webp",
    descripcion: "Juego de comedor para seis personas con mesa de madera y sillas tapizadas de diseño contemporáneo.",
    material: "Madera maciza y tela",
    color: "Nogal",
    dimensiones: "180 x 90 x 75 cm"},

    {id: "prod-08",
    nombre: "Comedor Luxury",
    precio: 3299,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor luxuri.jpg",
    descripcion: "Comedor de diseño elegante para seis personas.",
    material: "Madera y tela",
    color: "Nogal",
    dimensiones: "180 x 90 x 75 cm"},

    {id: "prod-09",
    nombre: "Comedor Nórdico",
    precio: 2899,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor nordico01.webp",
    descripcion: "Comedor de estilo nórdico con acabados modernos.",
    material: "Madera maciza",
    color: "Natural",
    dimensiones: "170 x 85 x 75 cm"},
        
    {id: "prod-10",
    nombre: "Comedor Elegance",
    precio: 3599,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor elegante.webp",
    descripcion: "Comedor premium de estilo contemporáneo.",
    material: "Madera y vidrio",
    color: "Marrón",
    dimensiones: "190 x 95 x 75 cm"},
    
    {id: "prod-11",
    nombre: "Comedor Roble",
    precio: 2799,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor de roble.jpg",
    descripcion: "Comedor fabricado en madera de roble.",
    material: "Roble macizo",
    color: "Roble",
    dimensiones: "180 x 90 x 75 cm"},
    
    {id: "prod-12",
    nombre: "Comedor Premium",
    precio: 3899,
    categoria: "Comedor",
    imagen: "../Img/comedor/comedor premium.webp",
    descripcion: "Comedor de lujo con acabados exclusivos.",
    material: "Madera premium y tela",
    color: "Nogal oscuro",
    dimensiones: "200 x 100 x 75 cm"},
    
    {id: "prod-13",
    nombre: "Vanitorio Moderno",
    precio: 1299,
    categoria: "Baño",
    imagen: "../Img/baño/vanitorio1.webp",
    descripcion: "Vanitorio moderno con acabado elegante y amplio espacio de almacenamiento.",
    material: "MDF y cerámica",
    color: "Blanco",
    dimensiones: "80 x 45 x 85 cm"},

    {id: "prod-14",
    nombre: "Espejo Aura Oval",
    precio: 499,
    categoria: "Baño",
    imagen: "../Img/baño/Espejo Aura Oval.webp",
    descripcion: "Espejo ovalado decorativo ideal para baños modernos.",
    material: "Vidrio y aluminio",
    color: "Negro",
    dimensiones: "80 x 50 cm"},
    
    {id: "prod-15",
    nombre: "Gabinete Nordic",
    precio: 899,
    categoria: "Baño",
    imagen: "../Img/baño/Gabinete Nordic.png",
    descripcion: "Gabinete de baño con diseño nórdico y múltiples compartimentos.",
    material: "MDF laminado",
    color: "Roble claro",
    dimensiones: "70 x 35 x 180 cm"},
    
    {id: "prod-16",
    nombre: "Mueble Lavamanos",
    precio: 1599,
    categoria: "Baño",
    imagen: "../Img/baño/Mueble Lavamanos.jpg",
    descripcion: "Mueble para lavamanos con almacenamiento integrado.",
    material: "Madera y cerámica",
    color: "Blanco",
    dimensiones: "100 x 50 x 85 cm"},
    
    {id: "prod-17",
    nombre: "Espejo LED Premium",
    precio: 699,
    categoria: "Baño",
    imagen: "../Img/baño/Espejo LED Premium.webp",
    descripcion: "Espejo con iluminación LED integrada y diseño moderno.",
    material: "Vidrio templado",
    color: "Plateado",
    dimensiones: "90 x 60 cm"},
    
    {id: "prod-18",
    nombre: "Organizador de Baño",
    precio: 349,
    categoria: "Baño",
    imagen: "../Img/baño/Organizador de Baño.png",
    descripcion: "Organizador práctico para mantener el baño ordenado.",
    material: "Madera MDF",
    color: "Blanco",
    dimensiones: "60 x 25 x 120 cm"
    }
    
    

    ];